//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace peilin
{
	/// <summary>
	/// Database       : mydb
	/// Data Source    : mydb
	/// Server Version : 3.24.0
	/// </summary>
	public partial class MydbDB : LinqToDB.Data.DataConnection
	{
		public ITable<Blow>        Blows        { get { return this.GetTable<Blow>(); } }
		public ITable<Camera>      Cameras      { get { return this.GetTable<Camera>(); } }
		public ITable<DefectCheck> DefectChecks { get { return this.GetTable<DefectCheck>(); } }
		public ITable<DefectCount> DefectCounts { get { return this.GetTable<DefectCount>(); } }
		public ITable<DefectType>  DefectTypes  { get { return this.GetTable<DefectType>(); } }
		public ITable<LastSetting> LastSettings { get { return this.GetTable<LastSetting>(); } }
		public ITable<Param>       @params      { get { return this.GetTable<Param>(); } }
		public ITable<Parameter>   Parameters   { get { return this.GetTable<Parameter>(); } }
		public ITable<Total>       Totals       { get { return this.GetTable<Total>(); } }
		public ITable<Type>        Types        { get { return this.GetTable<Type>(); } }
		public ITable<User>        Users        { get { return this.GetTable<User>(); } }

		public MydbDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MydbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MydbDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MydbDB(LinqToDBConnectionOptions<MydbDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("blow")]
	public partial class Blow
	{
		[Column("type"),         NotNull    ] public string Type        { get; set; } // varchar(30)
		[Column("name"),         NotNull    ] public string Name        { get; set; } // varchar(30)
		[Column("time"),         NotNull    ] public int    Time        { get; set; } // int
		[Column("stop"),            Nullable] public int?   Stop        { get; set; } // int
		[Column("chinese_name"),    Nullable] public string ChineseName { get; set; } // varchar(20)
	}

	[Table("camera")]
	public partial class Camera
	{
		[Column("type"),         NotNull    ] public string Type        { get; set; } // varchar(30)
		[Column("name"),         NotNull    ] public string Name        { get; set; } // varchar(20)
		[Column("value"),        NotNull    ] public string Value       { get; set; } // varchar(20)
		[Column("stop"),         NotNull    ] public int    Stop        { get; set; } // int
		[Column("chinese_name"),    Nullable] public string ChineseName { get; set; } // varchar(20)
	}

	[Table("defect_check")]
	public partial class DefectCheck
	{
		[Column("type"), NotNull    ] public string Type { get; set; } // varchar(30)
		[Column("stop"), NotNull] public int Stop { get; set; } // varchar(30)
		[Column("name"), NotNull    ] public string Name { get; set; } // varchar(20)
		[Column("Threshold"), NotNull] public string Threshold { get; set; } // double

		[Column("yn"), NotNull] public int?   Yn   { get; set; } // int
		[Column("chineseName"), NotNull] public string ChineseName { get; set; }

	}

	[Table("defect_count")]
	public partial class DefectCount
	{
		[Column("type"),   NotNull    ] public string   Type  { get; set; } // varchar(30)
		[Column("name"),   NotNull    ] public string   Name  { get; set; } // varchar(20)
		[Column("count"),  NotNull    ] public int      Count { get; set; } // int
		[Column("time"),   NotNull    ] public DateTime Time  { get; set; } // datetime
		[Column("lot_id"),    Nullable] public string   LotId { get; set; } // varchar(20)
	}

	[Table("defect_type")]
	public partial class DefectType
	{
		[Column("name"), NotNull] public string Name { get; set; } // varchar(30)
	}

	[Table("last_setting")]
	public partial class LastSetting
	{
		[Column("last_no_index"),   NotNull] public string LastNoIndex   { get; set; } // varchar(5)
		[Column("last_user_index"), NotNull] public string LastUserIndex { get; set; } // varchar(5)
		[Column("last_lotid"),      NotNull] public string LastLotid     { get; set; } // varchar(20)
		[Column("last_order"),      NotNull] public string LastOrder     { get; set; } // varchar(10)
		[Column("last_pack"),       NotNull] public string LastPack      { get; set; } // varchar(10)
		[Column("last_NGLimit"), NotNull] public string LastNGLimit { get; set; } //	
		[Column("last_NULLLimit"), NotNull] public string LastNULLLimit { get; set; } // varchar(10)
	}

	[Table("param")]
	public partial class Param
	{
		[Column("type"),         NotNull    ] public string Type        { get; set; } // varchar(30)
		[Column("name"),         NotNull    ] public string Name        { get; set; } // varchar(20)
		[Column("value"),        NotNull    ] public string Value       { get; set; } // varchar(20)
		[Column("stop"),            Nullable] public int?   Stop        { get; set; } // int
		[Column("chinese_name"),    Nullable] public string ChineseName { get; set; } // varchar(20)
	}

	[Table("parameter")]
	public partial class Parameter
	{
		[Column("name"),  Nullable] public string Name  { get; set; } // varchar(20)
		[Column("value"), Nullable] public string Value { get; set; } // varchar(20)
	}

	[Table("total")]
	public partial class Total
	{
		[Column("num"), NotNull] public int Num { get; set; } // int
	}

	[Table("type")]
	public partial class Type
	{
		[Column("type"), NotNull] public string TypeColumn { get; set; } // varchar(30)
		[Column(),       NotNull] public double ID         { get; set; } // float
		[Column(),       NotNull] public double OD         { get; set; } // float
		[Column(),       NotNull] public double H          { get; set; } // float
		[Column(),       NotNull] public string hasgroove   { get; set; } // varchar(30)
		[Column(),       NotNull] public string PTFEColor  { get; set; } // varchar(30)
		[Column(),       NotNull] public string material { get; set; } // varchar(30)
		[Column(),       NotNull] public string boxorpack { get; set; } // varchar(30)
		[Column(),       NotNull] public double thick { get; set; } // float
		[Column(),       NotNull] public string hasYZP { get; set; } // varchar(30)
	}

	[Table("user")]
	public partial class User
	{
		[Column("user_name"), NotNull] public string UserName { get; set; } // varchar(30)
		[Column("password"),  NotNull] public string Password { get; set; } // varchar(30)
		[Column("level"),     NotNull] public int    Level    { get; set; } // int
	}
}
